name: Oleksandr Ponomarov
title: hitchhiker's notes
email: ponomarov.aleksandr@gmail.com
description: >-
  A home for poorly researched ideas that I find myself repeating a lot anyway.

baseurl: "/"

permalink: /posts/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
