title: hitchhiker's notes
email: ponomarov.aleksandr@gmail.com
description: >-
  A home for poorly researched ideas that I find myself repeating a lot anyway.
twitter_username: sqrt16bit
github_username: shmileee

baseurl: "/"

theme: minima
plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title.html
