source "https://rubygems.org"

group :jekyll_plugins do
  gem "github-pages", "~> 232"
  gem "jekyll-feed", "~> 0.12"
  gem "minima", "~> 2.5"
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
